version: '2'
services:
  mongo:
    image: "mongo"
    container_name: mongo_container
    ports:
      - "27017:27017"

  flask:
    build:
      context: ./flask_bdgest/
      dockerfile: Dockerfile
    image: flask_image
    container_name: flask_container
    ports:
      - "1000:1000"
    volumes:
      - "$PWD/flask_bdgest:/home/flask"
    links: 
      - mongo
  scrapy:
    build:
      context: ./scrapy_bdgest/
      dockerfile: Dockerfile
    image: scrapy_image
    container_name: scrapy_container
    volumes:
      - "$PWD/scrapy_bdgest:/home/scrapy"
    links: 
      - mongo
