version: '2'
services:
  mongo:
    image: dhermanns/rpi-mongo
    container_name: mongo_container
    ports:
      - "27017:27017"

  flask:
    build:
      context: ./flask_bdgest/
      dockerfile: Dockerfile
    image: flask_image
    container_name: flask_container
    volumes:
      - "/home/pi/corners/bdgest/Evaluation/Projet/flask_bdgest:/home/flask"
    ports:
      - "1000:1000"
    links: 
      - mongo
  scrapy:
    build:
      context: ./scrapy_bdgest/
      dockerfile: Dockerfile
    image: scrapy_image
    container_name: scrapy_container
    volumes:
      - "/home/pi/corners/bdgest/Evaluation/Projet/scrapy_bdgest:/home/scrapy"
    links: 
      - mongo
